### ISSUE TITLE
"id is not specified for extension colors/ChroMATERIAL -- Darcula"

### ISSUE THREAD

**Issue by ForNeVeR** [ciscorucinski/ChroMATERIAL#45]
We are receiving a fair amount of error reports in Rider from the following stack trace, related to this plugin:
```
java.lang.Throwable: id is not specified for extension colors/ChroMATERIAL -- Darcula
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImplKt$createLoadBundledSchemeRequests$1$1.getSchemeKey(EditorColorsManagerImpl.kt:733)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadBundledSchemes(SchemeManagerImpl.kt:127)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.<init>(EditorColorsManagerImpl.kt:103)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.<init>(EditorColorsManagerImpl.kt:90)
	[…]
```

I think that there's some new-ish requirement in IntelliJ 2023.3, that now logs an error if there are any extensions defined in the `plugin.xml` without `id` defined. To avoid this, a small update to `plugin.xml` would be required. I think you can choose any meaningful id.

**Comment by ciscorucinski** [comment]
I haven't been active in development, but I will look at this more. 
It appears I do have an ID, so I found this recent issue: https://youtrack.jetbrains.com/issue/IDEA-337388/java.lang.Throwable-id-is-not-specified-for-extension-visualstudiocodedarkplus
